#!/usr/bin/env python3
"""Create a non-destructive, code-informed visual classification for ZMX1.

The classified tree uses NTFS hard links.  It is a browseable view over the
complete FFDec export, not another copy of the image data.
"""

from __future__ import annotations

import csv
import hashlib
import json
import os
import re
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
FULL_ROOT = ROOT / "assets" / "extracted" / "full" / "zmxiyou1"
# This detailed tree is an intermediate audit view.  The user-facing compact
# tree is generated by build_zmxiyou1_compact_view.py at classified/zmxiyou1.
OUTPUT_ROOT = ROOT / "assets" / "extracted" / "classified" / "zmxiyou1_detailed"
MANIFEST_PATH = ROOT / "sources" / "manifests" / "zmxiyou1_image_classification.json"
REPORT_PATH = ROOT / "sources" / "ZMXIYOU1_IMAGE_CLASSIFICATION.md"
VISUAL_EXTENSIONS = {".png", ".jpg", ".jpeg", ".svg"}


@dataclass(frozen=True)
class Package:
    key: str
    root: Path
    kind: str


PACKAGES = [
    Package("Role_v7", FULL_ROOT / "characters" / "mixed_packages" / "Role_v7", "role"),
    Package("Monster_v1", FULL_ROOT / "monsters" / "Monster_v1", "monster"),
    Package("Monster2_v4", FULL_ROOT / "monsters" / "Monster2_v4", "monster"),
    Package("Monster3_v3", FULL_ROOT / "monsters" / "Monster3_v3", "monster"),
    Package("OtherMat_v9", FULL_ROOT / "shared" / "OtherMat_v9", "ui_shared"),
    Package("backpack_v2", FULL_ROOT / "shared" / "backpack_v2", "ui_backpack"),
    Package("main_game", FULL_ROOT / "shared" / "main" / "main_game", "main"),
    Package("portal_loader", FULL_ROOT / "shared" / "portal_loader" / "portal_loader", "portal"),
    Package("portal_4399_gif", FULL_ROOT / "shared" / "portal_embedded" / "4399_gif", "portal"),
]


def safe_name(value: str, maximum: int = 64) -> str:
    value = re.sub(r"[<>:\"/\\|?*\x00-\x1f]", "_", value).strip(" .")
    value = re.sub(r"\s+", "_", value)
    return (value or "未命名")[:maximum]


def relative(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore") if path.exists() else ""


def read_symbols(package: Package) -> dict[int, str]:
    path = package.root / "symbolClass" / "symbols.csv"
    if not path.exists():
        return {}
    result: dict[int, str] = {}
    with path.open("r", encoding="utf-8", errors="replace", newline="") as handle:
        for row in csv.reader(handle, delimiter=";"):
            if len(row) >= 2 and row[0].isdigit():
                result[int(row[0])] = row[1]
    return result


def visual_character_id(package: Package, path: Path) -> int | None:
    parts = path.relative_to(package.root).parts
    if parts and parts[0] == "sprites" and len(parts) >= 2:
        match = re.match(r"DefineSprite_(\d+)(?:_|$)", parts[1])
        return int(match.group(1)) if match else None
    if parts and parts[0] == "buttons" and len(parts) >= 2:
        # Button exports use state filenames such as 1_up.png.  The SWF
        # character id is encoded in the parent DefineButton[2]_<id> folder,
        # not in the state number at the start of the filename.
        match = re.match(r"DefineButton(?:2)?_(\d+)(?:_|$)", parts[1])
        return int(match.group(1)) if match else None
    if parts and parts[0] in {"images", "shapes", "morphshapes"}:
        match = re.match(r"(\d+)(?:_|\.|$)", path.name)
        return int(match.group(1)) if match else None
    return None


def asset_type(package: Package, path: Path) -> str:
    parts = path.relative_to(package.root).parts
    return parts[0] if parts else "other"


def monster_catalog(packages: list[Package], symbols_by_package: dict[str, dict[int, str]]) -> tuple[dict[tuple[str, str], dict[str, object]], dict[tuple[str, str], str]]:
    catalog: dict[tuple[str, str], dict[str, object]] = {}
    effect_owner: dict[tuple[str, str], str] = {}
    for package in packages:
        if package.kind != "monster":
            continue
        symbols = symbols_by_package[package.key]
        roots: list[tuple[int, str]] = []
        for character_id, symbol_name in symbols.items():
            match = re.fullmatch(r"export\.monster\.(Monster\d+)", symbol_name)
            if not match:
                continue
            monster_class = match.group(1)
            script = package.root / "scripts" / "export" / "monster" / f"{monster_class}.as"
            text = read_text(script)
            name_match = re.search(r'monsterName\s*=\s*"([^"]+)"', text)
            display_name = name_match.group(1) if name_match else ""
            is_boss = bool(re.search(r"isBoss\s*=\s*true", text))
            folder = f"{monster_class}_{safe_name(display_name)}" if display_name else monster_class
            catalog[(package.key, monster_class)] = {
                "id": character_id,
                "class": monster_class,
                "name": display_name,
                "boss": is_boss,
                "folder": folder,
                "script": relative(script),
            }
            roots.append((character_id, monster_class))

        # An effect belongs to a monster only when its actual class script
        # references that exported symbol.  Prefix matching handles the
        # conventional Monster13Bullet1-style names.
        for character_id, symbol_name in symbols.items():
            leaf = symbol_name.rsplit(".", 1)[-1]
            owners: list[str] = []
            prefix = re.match(r"Monster(\d+)(?:Bullet|BeAttack|BG|Child)", leaf)
            if prefix:
                candidate = f"Monster{prefix.group(1)}"
                if (package.key, candidate) in catalog:
                    owners.append(candidate)
            for _root_id, monster_class in roots:
                script = Path(str(catalog[(package.key, monster_class)]["script"]))
                text = read_text(ROOT / script)
                if re.search(rf'[".]({re.escape(leaf)})[";.(]', text) or symbol_name in text:
                    owners.append(monster_class)
            owners = sorted(set(owners))
            if len(owners) == 1:
                effect_owner[(package.key, symbol_name)] = owners[0]
    return catalog, effect_owner


ROLE_ACTION_WORDS = ("攻击", "奔跑", "等待", "跳", "受伤", "弹跳", "落下")
ROLE_EFFECT_WORDS = (
    "Bullet", "冰柱", "加血", "cure", "升龙斩", "冲刺斩", "Fire",
    "hit7", "Hit10", "hit10", "Flush", "Effect",
)


def role_owner_and_kind(package: Package, character_id: int, symbol_name: str) -> tuple[str, str, str]:
    leaf = symbol_name.rsplit(".", 1)[-1]
    if symbol_name == "export.hero.Role1":
        return "人物/悟空_Role1/本体", "high", "symbolClass export.hero.Role1"
    if symbol_name in {"export.hero.Role2", "export.hero.Role2Shadow"}:
        return "人物/唐僧_Role2/本体", "high", f"symbolClass {symbol_name}"
    if leaf in {"HeroBeHurt", "MonsterBeHurt1", "MonsterBeHurt2", "WsEffect"}:
        return "特效/公共战斗特效", "high", f"共享效果类 {leaf}"

    owner = "唐僧_Role2" if character_id > 575 else "悟空_Role1"
    script_candidates = list((package.root / "scripts").rglob(f"{leaf}.as"))
    script_text = "\n".join(read_text(path) for path in script_candidates)
    if "Role1(this.parent)" in script_text:
        owner = "悟空_Role1"
    elif "Role2(this.parent)" in script_text or leaf.startswith("Role2"):
        owner = "唐僧_Role2"

    if any(word.lower() in symbol_name.lower() for word in ROLE_EFFECT_WORDS):
        return f"特效/{owner}", "high", f"角色效果类 {symbol_name}"
    if any(word in symbol_name for word in ROLE_ACTION_WORDS):
        return f"人物/{owner}/动作片段", "medium", f"角色动作符号 {symbol_name}"
    return f"待确认/Role_v7/命名零件/{owner}", "low", f"仅能按角色标签区间判断：{symbol_name}"


def ui_category(symbol_name: str, package_kind: str) -> tuple[str, str, str]:
    lower = symbol_name.lower()
    if package_kind == "ui_backpack":
        return "UI/背包", "high", "backpack_v2 专用资源包"
    if any(word in lower for word in ("bossblood", "gameinfo", "batter", "hurtnum", "bulnum", "blood")) or "血" in symbol_name or re.fullmatch(r"b?num\d", symbol_name):
        return "UI/HUD与血条", "high", f"HUD/数值符号 {symbol_name}"
    if any(word in lower for word in ("skill", "buyskill", "passiveskill", "shop")) or "技能" in symbol_name:
        return "UI/技能界面", "high", f"技能界面符号 {symbol_name}"
    if any(word in lower for word in ("menu", "help", "about", "gamefail", "select", "roleinfo", "alert", "loading", "cue")):
        return "UI/菜单与面板", "high", f"菜单/面板符号 {symbol_name}"
    if package_kind == "ui_shared":
        return "UI/公共界面与图标", "medium", "OtherMat_v9 公共界面资源包"
    if package_kind == "portal":
        return "UI/4399外壳", "high", "网页外壳资源包"
    return "待确认/主程序命名符号", "low", f"主程序符号 {symbol_name}"


def category_for_symbol(
    package: Package,
    character_id: int,
    symbol_name: str,
    monster_catalog_data: dict[tuple[str, str], dict[str, object]],
    monster_effect_owner: dict[tuple[str, str], str],
) -> tuple[str, str, str]:
    if package.kind == "role":
        return role_owner_and_kind(package, character_id, symbol_name)
    if package.kind == "monster":
        root_match = re.fullmatch(r"export\.monster\.(Monster\d+)", symbol_name)
        if root_match:
            monster_class = root_match.group(1)
            info = monster_catalog_data[(package.key, monster_class)]
            return f"怪物/{info['folder']}/本体", "high", f"导出怪物根类 {symbol_name}"
        owner = monster_effect_owner.get((package.key, symbol_name))
        if owner is not None:
            info = monster_catalog_data[(package.key, owner)]
            return f"怪物/{info['folder']}/特效", "high", f"{info['script']} 实际引用 {symbol_name}"
        if symbol_name == "BossBlood":
            return "UI/HUD与血条", "high", "BossBlood 原版 Boss 血条"
        if symbol_name == "BossDead" or symbol_name.startswith("export.aura.") or symbol_name in {"poisonUp", "poisonHead", "ice"}:
            return "特效/怪物公共特效", "high", f"怪物公共效果 {symbol_name}"
        return f"待确认/{package.key}/怪物命名零件", "low", f"未发现唯一怪物代码引用：{symbol_name}"
    if package.kind in {"ui_shared", "ui_backpack", "portal"}:
        return ui_category(symbol_name, package.kind)
    if package.kind == "main":
        if symbol_name in {"export.GameInfo", "export.LoadingBar", "GOGO", "LoginAlert", "export.ComeBackAlert", "export.FirstAlert", "export.OldCue", "export.NewCue"}:
            return ui_category(symbol_name, package.kind)
        return "待确认/场景与地图/命名符号", "medium", f"主程序场景符号 {symbol_name}"
    return f"待确认/{package.key}/命名符号", "low", symbol_name


def fallback_category(package: Package, path: Path) -> tuple[str, str, str]:
    kind = asset_type(package, path)
    if package.kind == "ui_backpack":
        return "UI/背包/未命名素材", "medium", "来自 backpack_v2"
    if package.kind == "ui_shared":
        return "UI/公共界面与图标/未命名素材", "medium", "来自 OtherMat_v9"
    if package.kind == "portal":
        return "UI/4399外壳/未命名素材", "medium", "来自网页外壳"
    if package.kind == "main":
        return f"待确认/场景与地图/{kind}", "low", "主程序未命名视觉资源"
    return f"待确认/{package.key}/{kind}", "low", "没有 symbolClass 或唯一代码引用"


def destination_for(
    package: Package,
    source: Path,
    category: str,
    character_id: int | None,
    symbol_name: str,
) -> Path:
    kind = asset_type(package, source)
    digest = hashlib.sha1(relative(source).encode("utf-8")).hexdigest()[:10]
    if character_id is not None:
        symbol_folder = f"symbol_{character_id}_{safe_name(symbol_name, 48)}"
        # A button/sprite symbol can contain several nested timelines whose
        # exported frames share names such as 1.png or 1_up.png.  Prefix the
        # original-path hash so the classified view remains collision-free.
        frame_name = f"{digest}_{safe_name(source.name, 80)}"
        return OUTPUT_ROOT / category / package.key / symbol_folder / kind / frame_name
    return OUTPUT_ROOT / category / package.key / kind / f"{digest}_{safe_name(source.name, 80)}"


def link_file(source: Path, destination: Path) -> str:
    destination.parent.mkdir(parents=True, exist_ok=True)
    if destination.exists():
        if os.path.samefile(source, destination):
            return "existing_hardlink"
        raise RuntimeError(f"Classification destination already exists: {destination}")
    os.link(source, destination)
    return "hardlink"


def main() -> None:
    if not FULL_ROOT.exists():
        raise SystemExit(f"Missing full extraction: {FULL_ROOT}")
    if OUTPUT_ROOT.exists() and any(OUTPUT_ROOT.iterdir()):
        raise SystemExit(f"Classification output is not empty: {OUTPUT_ROOT}")

    symbols_by_package = {package.key: read_symbols(package) for package in PACKAGES}
    monsters, monster_effect_owner = monster_catalog(PACKAGES, symbols_by_package)
    records: list[dict[str, object]] = []
    category_counts: Counter[str] = Counter()
    confidence_counts: Counter[str] = Counter()

    for package in PACKAGES:
        if not package.root.exists():
            continue
        symbols = symbols_by_package[package.key]
        visual_files = sorted(
            path for path in package.root.rglob("*")
            if path.is_file() and path.suffix.lower() in VISUAL_EXTENSIONS
        )
        for source in visual_files:
            character_id = visual_character_id(package, source)
            symbol_name = symbols.get(character_id, "") if character_id is not None else ""
            if symbol_name:
                category, confidence, evidence = category_for_symbol(
                    package,
                    character_id,
                    symbol_name,
                    monsters,
                    monster_effect_owner,
                )
            else:
                category, confidence, evidence = fallback_category(package, source)
            destination = destination_for(package, source, category, character_id, symbol_name)
            link_mode = link_file(source, destination)
            record = {
                "source": relative(source),
                "destination": relative(destination),
                "package": package.key,
                "asset_type": asset_type(package, source),
                "character_id": character_id,
                "symbol_name": symbol_name,
                "category": category,
                "confidence": confidence,
                "evidence": evidence,
                "link_mode": link_mode,
                "bytes": source.stat().st_size,
            }
            records.append(record)
            category_counts[category] += 1
            confidence_counts[confidence] += 1

    generated_at = datetime.now().astimezone().isoformat(timespec="seconds")
    monster_rows = sorted(monsters.values(), key=lambda row: int(str(row["class"])[7:]))
    manifest = {
        "generated_at": generated_at,
        "source_root": relative(FULL_ROOT),
        "classified_root": relative(OUTPUT_ROOT),
        "storage": "NTFS hard links; no image data duplication",
        "policy": "Code and symbolClass evidence first; uncertain anonymous assets stay in 待确认.",
        "playable_roles": [
            {"class": "Role1", "name": "悟空"},
            {"class": "Role2", "name": "唐僧"},
        ],
        "monsters": monster_rows,
        "counts_by_category": dict(sorted(category_counts.items())),
        "counts_by_confidence": dict(sorted(confidence_counts.items())),
        "files": records,
    }
    MANIFEST_PATH.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST_PATH.write_text(
        json.dumps(manifest, ensure_ascii=False, indent=2),
        encoding="utf-8",
        newline="\n",
    )

    lines = [
        "# 《造梦西游1》图片用途分类",
        "",
        f"生成时间：{generated_at}",
        "",
        f"已建立 **{len(records):,} 个硬链接**；它们不复制图片数据，原始拆包位于 `{relative(FULL_ROOT)}`。",
        "分类视图只用于浏览和挑选。修改硬链接内容会同时修改原文件，因此建议只查看和复制，不要直接编辑。",
        "",
        "## 分类原则",
        "",
        "- 人物与怪物本体：以 `symbolClass` 导出的根类为准。",
        "- 子弹与技能：以 `RoleN.as` / `MonsterN.as` 中的真实字符串调用为准。",
        "- UI：依据 backpack、OtherMat、主程序模块及符号名称归类。",
        "- 匿名 Timeline、元件和无法唯一反查的底层位图进入 `待确认`，不强行猜测。",
        "",
        "## 统计",
        "",
        "| 分类 | 文件数 |",
        "| --- | ---: |",
    ]
    lines.extend(f"| `{category}` | {count:,} |" for category, count in sorted(category_counts.items()))
    lines.extend(
        [
            "",
            "## 怪物目录",
            "",
            "| 类 | 原作名称 | Boss | 来源包 |",
            "| --- | --- | --- | --- |",
        ]
    )
    lines.extend(
        f"| {row['class']} | {row['name'] or '未写明'} | {'是' if row['boss'] else '否'} | {Path(str(row['script'])).parts[-5] if len(Path(str(row['script'])).parts) >= 5 else ''} |"
        for row in monster_rows
    )
    lines.extend(
        [
            "",
            f"完整逐文件依据见 `{relative(MANIFEST_PATH)}`。",
            "",
        ]
    )
    report = "\n".join(lines)
    REPORT_PATH.write_text(report, encoding="utf-8", newline="\n")
    (OUTPUT_ROOT / "README.md").write_text(report, encoding="utf-8", newline="\n")

    print(
        json.dumps(
            {
                "files": len(records),
                "roles": 2,
                "monsters": len(monster_rows),
                "categories": len(category_counts),
                "confidence": dict(confidence_counts),
                "classified_root": relative(OUTPUT_ROOT),
                "manifest": relative(MANIFEST_PATH),
                "report": relative(REPORT_PATH),
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
